version: '3.8'

services:
  negarin-db:
    image: mariadb:10
    container_name: negarin-mysql
    environment:
      MYSQL_DATABASE: negarin
      MYSQL_USER: negarin
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - negarin_db_data:/var/lib/mysql
    networks:
      - negarin_network

  negarin-redis:
    image: redis:7-alpine
    container_name: negarin-redis
    networks:
      - negarin_network

  negarin-web:
    image: php:8.3-apache
    container_name: negarin-web
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - negarin-db
      - negarin-redis
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://193.36.85.235:8080
      - APP_DOMAIN=localhost
      - DB_HOST=negarin-db
      - DB_DATABASE=negarin
      - DB_USERNAME=negarin
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=negarin-redis
      - REDIS_PORT=6379
    networks:
      - negarin_network

volumes:
  negarin_db_data:

networks:
  negarin_network:
    driver: bridge